import json
import os
import sys
from datetime import datetime


def generate_report(results_dir, output_file):
    """
    Aggregates JSON test result artifacts into a professional Markdown certification report.
    Part of the 'Luxurious Proof' (贅沢な証跡) CI pattern.
    """
    results = []
    if not os.path.exists(results_dir):
        print(f"Error: Results directory {results_dir} not found.")
        return

    for filename in os.listdir(results_dir):
        if filename.endswith(".json"):
            with open(os.path.join(results_dir, filename), "r") as f:
                try:
                    results.append(json.load(f))
                except json.JSONDecodeError:
                    print(f"Warning: Could not parse {filename}")

    if not results:
        print("No results found to report.")
        return

    # Sort results for consistent table presentation
    results.sort(
        key=lambda x: (x.get("os", ""), x.get("node", ""), x.get("python", ""))
    )

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    md_content = "# Verified Environments Report\n\n"
    md_content += f"**Last Updated**: {now} (Automated CI)\n\n"
    md_content += "| OS | Node.js | Python | Status | Timestamp |\n"
    md_content += "| --- | --- | --- | --- | --- |\n"

    for r in results:
        status_emoji = "✅ PASS" if r.get("status") == "pass" else "❌ FAIL"
        md_content += f"| {r.get('os')} | {r.get('node')} | {r.get('python')} | {status_emoji} | {r.get('timestamp')} |\n"

    md_content += "\n\n---\n*This report is automatically generated by GitHub Actions for every successful build.*"

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(md_content)

    print(f"Report generated successfully: {output_file}")


if __name__ == "__main__":
    # DUAL MODE OPERATION:
    # 1. Individual mode: --single <os> <node> <python> <status>
    # 2. Aggregation mode: (no arguments)
    if len(sys.argv) > 1 and sys.argv[1] == "--single":
        res = {
            "os": sys.argv[2],
            "node": sys.argv[3],
            "python": sys.argv[4],
            "status": sys.argv[5],
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        }
        os.makedirs("test-results", exist_ok=True)
        filename = f"result-{res['os']}-{res['node']}-{res['python']}.json"
        with open(os.path.join("test-results", filename), "w") as f:
            json.dump(res, f)
    else:
        generate_report("test-results", "VERIFIED_ENVIRONMENTS.md")
