import os
import datetime

# Configuration
RESULTS_DIR = "results"
OUTPUT_FILE = "COMPATIBILITY.md"

def generate_report():
    """
    Parses status files from a matrix build and generates a Markdown compatibility table.
    
    EXPECTED FILE STRUCTURE:
    results/
      result-ubuntu-latest-3.9/status.txt
      result-ubuntu-latest-3.10/status.txt
      ...
    """
    os_list = ["ubuntu-latest", "windows-latest", "macos-latest"]
    py_versions = ["3.9", "3.10", "3.11", "3.12"]
    
    table_data = {}
    
    for os_name in os_list:
        for py_ver in py_versions:
            path = os.path.join(RESULTS_DIR, f"result-{os_name}-{py_ver}", "status.txt")
            if os.path.exists(path):
                with open(path, "r", encoding="utf-8") as f:
                    status = f.read().strip()
                table_data[(os_name, py_ver)] = "✅ Pass" if status == "Pass" else "❌ Fail"
            else:
                table_data[(os_name, py_ver)] = "⏳ N/A"

    # Build Markdown
    header = "# LogicHive Compatibility Registry\n\n"
    header += f"Last Updated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    
    table = "| OS | " + " | ".join([f"Python {v}" for v in py_versions]) + " |\n"
    table += "|:---| " + " | ".join([":---:"] * len(py_versions)) + " |\n"
    
    for os_name in os_list:
        row = f"| **{os_name}** | "
        row += " | ".join([table_data.get((os_name, v), "⏳ N/A") for v in py_versions])
        row += " |\n"
        table += row

    footer = "\n*This report is automatically generated by GitHub Actions.*\n"
    
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(header + table + footer)

if __name__ == "__main__":
    generate_report()
